In [1]:
import numpy as np
import pandas as pd
import matplotlib as mp
from sklearn.linear_model import LogisticRegression, LassoLarsIC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.feature_selection import RFECV
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeRegressor

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
#census=pd.read_csv("data_inc.csv")
census=pd.read_csv(r"D:\Study\Sem 2\Programming for Data Science\Project\cleaned_censusoriginal.csv")
census.head(5)

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AGI,*(pred),AHRSPAY,AHSCOL,AMARITL,AMJIND,AMJOCC,ARACE,AREORGN,ASEX,AUNMEM,AUNTYPE,AWKSTAT,CAPGAIN,CAPLOSS,DIVVAL,FEDTAX,GRINGREG,GRINST,HHDFMX,HHDREL,MARSUPWT,MIGMTR1,MIGMTR3,MIGMTR4,MIGSAME,MIGSUN,NOEMP,PARENT,FATHER,MOTHER,SELF,PRCITSHP,SEOTR,VETQVA,VETYN,WKSWORK,YEAR,INCOME
0,73,Not in universe,0,0,High school graduate,NaN,0,NaN,Not in universe,Widowed,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Other Rel 18+ ever marr not in subfamily,Other relative of householder,1700.09,?,?,?,Not in universe under 1 year old,?,0,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,0
1,58,Self-employed-not incorporated,4,34,Some college but no degree,NaN,0,NaN,Not in universe,Divorced,Construction,Precision production craft & repair,White,All other,Male,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Head of household,South,Arkansas,Householder,Householder,1053.55,MSA to MSA,Same county,Same county,No,Yes,1,Not in universe,FATHER,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,0
2,18,Not in universe,0,0,10th grade,NaN,0,NaN,High school,Never married,Not in universe or children,Not in universe,Asian or Pacific Islander,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Child 18+ never marr Not in a subfamily,Child 18 or older,991.95,?,?,?,Not in universe under 1 year old,?,0,Not in universe,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,0
3,9,Not in universe,0,0,Children,NaN,0,NaN,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1758.14,Nonmover,Nonmover,Nonmover,Yes,Not in universe,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,0
4,10,Not in universe,0,0,Children,NaN,0,NaN,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1069.16,Nonmover,Nonmover,Nonmover,Yes,Not in universe,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,0

In [5]:
census.shape

(199523, 44)

In [6]:
census.columns

Index(['AAGE', 'ACLSWKR', 'ADTIND', 'ADTOCC', 'AHGA', 'AGI', '*(pred)',
       'AHRSPAY', 'AHSCOL', 'AMARITL', 'AMJIND', 'AMJOCC', 'ARACE', 'AREORGN',
       'ASEX', 'AUNMEM', 'AUNTYPE', 'AWKSTAT', 'CAPGAIN', 'CAPLOSS', 'DIVVAL',
       'FEDTAX', 'GRINGREG', 'GRINST', 'HHDFMX', 'HHDREL', 'MARSUPWT',
       'MIGMTR1', 'MIGMTR3', 'MIGMTR4', 'MIGSAME', 'MIGSUN', 'NOEMP', 'PARENT',
       'FATHER', 'MOTHER', 'SELF', 'PRCITSHP', 'SEOTR', 'VETQVA', 'VETYN',
       'WKSWORK', 'YEAR', 'INCOME'],
      dtype='object')

In [7]:
for c in census.columns:
    print("---- %s ---" % c)
    print(census[c].value_counts())

---- AAGE ---
34    3489
35    3450
36    3353
31    3351
33    3340
5     3332
4     3318
3     3279
37    3278
38    3277
2     3236
7     3218
30    3203
32    3188
8     3187
6     3171
9     3162
13    3152
39    3144
1     3138
41    3134
10    3134
11    3128
40    3114
14    3068
12    3060
29    3050
28    3013
42    2995
15    2926
      ...
60    1560
65    1550
62    1531
63    1501
61    1497
67    1496
66    1443
68    1436
71    1418
69    1412
70    1410
73    1354
72    1315
74    1227
75    1065
76    1050
77     979
78     876
79     811
80     799
90     725
81     720
82     615
83     561
84     519
85     423
86     348
87     301
88     241
89     195
Name: AAGE, Length: 91, dtype: int64
---- ACLSWKR ---
 Not in universe                   100245
 Private                            72028
 Self-employed-not incorporated      8445
 Local government                    7784
 State government                    4227
 Self-employed-incorporated          3265
 Federal government                  2925
 Never worked                         439
 Without pay                          165
Name: ACLSWKR, dtype: int64
---- ADTIND ---
0     100684
33     17070
43      8283
4       5984
42      4683
45      4482
29      4209
37      4022
41      3964
32      3596
35      3380
39      2937
34      2765
44      2549
2       2196
11      1764
50      1704
40      1651
47      1644
38      1629
24      1503
12      1350
19      1346
30      1181
31      1178
25      1084
9        993
22       952
36       945
13       899
1        827
48       652
27       626
49       610
3        563
21       559
6        554
5        553
8        550
16       539
23       525
18       483
15       452
7        422
14       295
46       187
17       157
28       143
26       127
51        36
20        32
10         4
Name: ADTIND, dtype: int64
---- ADTOCC ---
0     100684
2       8756
26      7887
19      5413
29      5105
36      4145
34      4025
10      3683
16      3445
23      3392
12      3340
33      3325
3       3195
35      3168
38      3003
31      2699
32      2398
37      2234
8       2151
42      1918
30      1897
24      1847
17      1771
28      1661
44      1592
41      1592
43      1382
4       1364
13      1271
18      1083
39      1017
14       932
5        855
15       815
27       780
25       767
9        738
7        731
11       637
40       617
1        544
21       533
6        441
22       411
45       172
20        71
46        36
Name: ADTOCC, dtype: int64
---- AHGA ---
 High school graduate                      48407
 Children                                  47422
 Some college but no degree                27820
 Bachelors degree(BA AB BS)                19865
 7th and 8th grade                          8007
 10th grade                                 7557
 11th grade                                 6876
 Masters degree(MA MS MEng MEd MSW MBA)     6541
 9th grade                                  6230
 Associates degree-occup /vocational        5358
 Associates degree-academic program         4363
 5th or 6th grade                           3277
 12th grade no diploma                      2126
 1st 2nd 3rd or 4th grade                   1799
 Prof school degree (MD DDS DVM LLB JD)     1793
 Doctorate degree(PhD EdD)                  1263
 Less than 1st grade                         819
Name: AHGA, dtype: int64
---- AGI ---
Series([], Name: AGI, dtype: int64)
---- *(pred) ---
0       188219
500        734
600        546
700        534
800        507
1000       386
425        376
900        336
550        280
1200       256
1100       235
650        229
450        222
1500       221
750        202
1300       198
850        167
525        147
1600       136
1400       132
1800       127
400        125
1700       116
2000       108
475        105
435         98
625         91
950         84
1050        76
575         73
         ...
807          1
2470         1
458          1
1446         1
1190         1
2377         1
586          1
4900         1
1266         1
1394         1
294          1
1829         1
1191         1
1353         1
552          1
626          1
742          1
1224         1
1960         1
2291         1
2163         1
1096         1
1638         1
1905         1
487          1
743          1
584          1
170          1
1265         1
2142         1
Name: *(pred), Length: 1240, dtype: int64
---- AHRSPAY ---
Series([], Name: AHRSPAY, dtype: int64)
---- AHSCOL ---
 Not in universe          186943
 High school                6892
 College or university      5688
Name: AHSCOL, dtype: int64
---- AMARITL ---
 Never married                      86485
 Married-civilian spouse present    84222
 Divorced                           12710
 Widowed                            10463
 Separated                           3460
 Married-spouse absent               1518
 Married-A F spouse present           665
Name: AMARITL, dtype: int64
---- AMJIND ---
 Not in universe or children            100684
 Retail trade                            17070
 Manufacturing-durable goods              9015
 Education                                8283
 Manufacturing-nondurable goods           6897
 Finance insurance and real estate        6145
 Construction                             5984
 Business and repair services             5651
 Medical except hospital                  4683
 Public administration                    4610
 Other professional services              4482
 Transportation                           4209
 Hospital services                        3964
 Wholesale trade                          3596
 Agriculture                              3023
 Personal services except private HH      2937
 Social services                          2549
 Entertainment                            1651
 Communications                           1181
 Utilities and sanitary services          1178
 Private household services                945
 Mining                                    563
 Forestry and fisheries                    187
 Armed Forces                               36
Name: AMJIND, dtype: int64
---- AMJOCC ---
 Not in universe                          100684
 Adm support including clerical            14837
 Professional specialty                    13940
 Executive admin and managerial            12495
 Other service                             12099
 Sales                                     11783
 Precision production craft & repair       10518
 Machine operators assmblrs & inspctrs      6379
 Handlers equip cleaners etc                4127
 Transportation and material moving         4020
 Farming forestry and fishing               3146
 Technicians and related support            3018
 Protective services                        1661
 Private household services                  780
 Armed Forces                                 36
Name: AMJOCC, dtype: int64
---- ARACE ---
 White                          167365
 Black                           20415
 Asian or Pacific Islander        5835
 Other                            3657
 Amer Indian Aleut or Eskimo      2251
Name: ARACE, dtype: int64
---- AREORGN ---
 All other                    171907
 Mexican-American               8079
 Mexican (Mexicano)             7234
 Central or South American      3895
 Puerto Rican                   3313
 Other Spanish                  2485
 Cuban                          1126
 NA                              874
 Do not know                     306
 Chicano                         304
Name: AREORGN, dtype: int64
---- ASEX ---
 Female    103984
 Male       95539
Name: ASEX, dtype: int64
---- AUNMEM ---
 Not in universe    180459
 No                  16034
 Yes                  3030
Name: AUNMEM, dtype: int64
---- AUNTYPE ---
 Not in universe          193453
 Other job loser            2038
 Re-entrant                 2019
 Job loser - on layoff       976
 Job leaver                  598
 New entrant                 439
Name: AUNTYPE, dtype: int64
---- AWKSTAT ---
 Children or Armed Forces              123769
 Full-time schedules                    40736
 Not in labor force                     26808
 PT for non-econ reasons usually FT      3322
 Unemployed full-time                    2311
 PT for econ reasons usually PT          1209
 Unemployed part- time                    843
 PT for econ reasons usually FT           525
Name: AWKSTAT, dtype: int64
---- CAPGAIN ---
0        192144
15024       788
7688        609
7298        582
99999       390
3103        237
5178        207
5013        158
4386        151
3325        121
8614        118
10520        98
27828        94
4650         93
20051        91
594          88
4064         83
2174         83
1086         81
14084        77
1409         77
13550        74
2829         71
10605        70
9386         70
1055         69
3464         67
2329         66
6849         65
2964         65
          ...
2961         14
18481        14
10566        13
2036         11
15020        11
34095        11
114          11
9562         10
1831          9
4687          9
5721          9
1731          5
7262          5
5060          5
6360          4
2098          4
1111          4
3800          3
22040         2
2774          2
1090          2
41310         2
6612          1
9472          1
8530          1
2227          1
4594          1
2387          1
1140          1
2601          1
Name: CAPGAIN, Length: 132, dtype: int64
---- CAPLOSS ---
0       195617
1902       407
1977       381
1887       364
1602       193
2415       122
1485        95
1848        88
1876        87
1672        85
1590        84
1740        72
2339        61
1564        60
1980        59
1741        58
1408        56
1719        56
2001        56
2258        56
1669        55
1974        51
2002        51
2377        48
2205        46
1579        43
1721        42
1668        39
2051        38
2559        38
         ...
1594         8
2238         7
2788         7
1380         7
2282         7
653          7
2090         6
810          5
2465         5
772          5
3770         5
1021         4
2472         4
4608         4
1755         4
1138         4
3683         4
2597         3
2722         3
2754         3
2027         2
2201         2
1640         2
1956         2
3900         2
974          2
155          1
2080         1
2519         1
1911         1
Name: CAPLOSS, Length: 113, dtype: int64
---- DIVVAL ---
0        178382
100        1148
500        1030
1000        894
200         866
50          832
2000        574
250         555
150         549
300         523
1           472
400         409
1500        380
2500        372
25          360
5000        304
3000        292
600         287
10          253
4000        222
20          213
2           193
10000       182
5           179
125         175
75          169
750         164
30          163
12          146
60          142
          ...
667           1
358           1
1895          1
9119          1
3098          1
47558         1
2640          1
5349          1
593           1
2205          1
284           1
4382          1
8600          1
999           1
2104          1
796           1
1361          1
26000         1
1948          1
7506          1
4197          1
541           1
2844          1
2022          1
998           1
568           1
1309          1
21100         1
5663          1
5024          1
Name: DIVVAL, Length: 1478, dtype: int64
---- FEDTAX ---
 Nonfiler                        75094
 Joint both under 65             67383
 Single                          37421
 Joint both 65+                   8332
 Head of household                7426
 Joint one under 65 & one 65+     3867
Name: FEDTAX, dtype: int64
---- GRINGREG ---
 Not in universe    183750
 South                4889
 West                 4074
 Midwest              3575
 Northeast            2705
 Abroad                530
Name: GRINGREG, dtype: int64
---- GRINST ---

 Not in universe         183750
 California                1714
 Utah                      1063
 Florida                    849
 North Carolina             812
 ?                          708
 Abroad                     671
 Oklahoma                   626
 Minnesota                  576
 Indiana                    533
 North Dakota               499
 New Mexico                 463
 Michigan                   441
 Alaska                     290
 Kentucky                   244
 Arizona                    243
 New Hampshire              242
 Wyoming                    241
 Colorado                   239
 Oregon                     236
 West Virginia              231
 Georgia                    227
 Montana                    226
 Alabama                    216
 Ohio                       211
 Texas                      209
 Arkansas                   205
 Mississippi                204
 Tennessee                  202
 Pennsylvania               199
 New York                   195
 Louisiana                  192
 Vermont                    191
 Iowa                       189
 Illinois                   180
 Nebraska                   178
 Missouri                   175
 Nevada                     174
 Maine                      167
 Massachusetts              151
 Kansas                     149
 South Dakota               138
 Maryland                   136
 Virginia                   126
 Connecticut                117
 District of Columbia       116
 Wisconsin                  105
 South Carolina              95
 New Jersey                  75
 Delaware                    73
 Idaho                       31
Name: GRINST, dtype: int64
---- HHDFMX ---
 Householder                                        53248
 Child <18 never marr not in subfamily              50326
 Spouse of householder                              41695
 Nonfamily householder                              22213
 Child 18+ never marr Not in a subfamily            12030
 Secondary individual                                6122
 Other Rel 18+ ever marr not in subfamily            1956
 Grandchild <18 never marr child of subfamily RP     1868
 Other Rel 18+ never marr not in subfamily           1728
 Grandchild <18 never marr not in subfamily          1066
 Child 18+ ever marr Not in a subfamily              1013
 Child under 18 of RP of unrel subfamily              732
 RP of unrelated subfamily                            685
 Child 18+ ever marr RP of subfamily                  671
 Other Rel <18 never marr child of subfamily RP       656
 Other Rel 18+ ever marr RP of subfamily              656
 Other Rel 18+ spouse of subfamily RP                 638
 Child 18+ never marr RP of subfamily                 589
 Other Rel <18 never marr not in subfamily            584
 Grandchild 18+ never marr not in subfamily           375
 In group quarters                                    196
 Child 18+ spouse of subfamily RP                     126
 Other Rel 18+ never marr RP of subfamily              94
 Child <18 never marr RP of subfamily                  80
 Spouse of RP of unrelated subfamily                   52
 Child <18 ever marr not in subfamily                  36
 Grandchild 18+ ever marr not in subfamily             34
 Grandchild 18+ spouse of subfamily RP                 10
 Child <18 ever marr RP of subfamily                    9
 Grandchild 18+ ever marr RP of subfamily               9
 Other Rel <18 ever marr RP of subfamily                6
 Grandchild 18+ never marr RP of subfamily              6
 Other Rel <18 never married RP of subfamily            4
 Other Rel <18 spouse of subfamily RP                   3
 Child <18 spouse of subfamily RP                       2
 Grandchild <18 never marr RP of subfamily              2
 Grandchild <18 ever marr not in subfamily              2
 Other Rel <18 ever marr not in subfamily               1
Name: HHDFMX, dtype: int64
---- HHDREL ---
 Householder                             75475
 Child under 18 never married            50426
 Spouse of householder                   41709
 Child 18 or older                       14430
 Other relative of householder            9703
 Nonrelative of householder               7601
 Group Quarters- Secondary individual      132
 Child under 18 ever married                47
Name: HHDREL, dtype: int64
---- MARSUPWT ---
1601.40    32
753.23     32
1191.21    32
1787.34    32
707.90     31
1317.51    31
1070.15    30
1839.19    28
1002.02    28
1009.39    28
1033.83    28
1029.73    27
1122.60    27
1528.84    27
964.50     26
1244.66    26
1011.71    26
1155.20    26
988.79     26
1882.96    26
974.01     26
1218.82    26
1138.19    25
1739.89    25
1032.82    25
1888.13    25
1224.90    25
1184.69    25
1022.93    24
812.13     24
           ..
2298.47     1
1128.55     1
1947.22     1
809.41      1
1160.64     1
810.59      1
843.23      1
2081.13     1
1816.23     1
1591.24     1
744.67      1
2840.59     1
1106.60     1
2051.77     1
2758.66     1
5358.66     1
2563.43     1
814.29      1
1648.00     1
453.09      1
558.09      1
958.97      1
2342.01     1
2227.15     1
2032.31     1
1043.52     1
1967.15     1
790.20      1
1052.48     1
384.00      1
Name: MARSUPWT, Length: 99800, dtype: int64
---- MIGMTR1 ---
 ?                   99696
 Nonmover            82538
 MSA to MSA          10601
 NonMSA to nonMSA     2811
 Not in universe      1516
 MSA to nonMSA         790
 NonMSA to MSA         615
 Abroad to MSA         453
 Not identifiable      430
 Abroad to nonMSA       73
Name: MIGMTR1, dtype: int64
---- MIGMTR3 ---
 ?                                 99696
 Nonmover                          82538
 Same county                        9812
 Different county same state        2797
 Not in universe                    1516
 Different region                   1178
 Different state same division       991
 Abroad                              530
 Different division same region      465
Name: MIGMTR3, dtype: int64
---- MIGMTR4 ---
 ?                               99696
 Nonmover                        82538
 Same county                      9812
 Different county same state      2797
 Not in universe                  1516
 Different state in South          973
 Different state in West           679
 Different state in Midwest        551
 Abroad                            530
 Different state in Northeast      431
Name: MIGMTR4, dtype: int64
---- MIGSAME ---
 Not in universe under 1 year old    101212
 Yes                                  82538
 No                                   15773
Name: MIGSAME, dtype: int64
---- MIGSUN ---
 ?                  99696
 Not in universe    84054
 No                  9987
 Yes                 5786
Name: MIGSUN, dtype: int64
---- NOEMP ---
0    95983
6    36511
1    23109
4    14379
3    13425
2    10081
5     6035
Name: NOEMP, dtype: int64
---- PARENT ---
 Not in universe           144232
 Both parents present       38983
 Mother only present        12772
 Father only present         1883
 Neither parent present      1653
Name: PARENT, dtype: int64
---- FATHER ---
 United-States                   159162
 Mexico                           10008
 ?                                 6713
 Puerto-Rico                       2680
 Italy                             2212
 Canada                            1380
 Germany                           1356
 Dominican-Republic                1290
 Poland                            1212
 Philippines                       1154
 Cuba                              1125
 El-Salvador                        982
 China                              856
 England                            793
 Columbia                           614
 India                              580
 South Korea                        530
 Ireland                            508
 Jamaica                            463
 Vietnam                            457
 Guatemala                          445
 Japan                              392
 Portugal                           388
 Ecuador                            379
 Haiti                              351
 Greece                             344
 Peru                               335
 Nicaragua                          315
 Hungary                            306
 Scotland                           247
 Iran                               233
 Yugoslavia                         217
 Taiwan                             199
 Cambodia                           196
 Honduras                           194
 France                             191
 Outlying-U S (Guam USVI etc)       159
 Laos                               154
 Trinadad&Tobago                    113
 Thailand                           107
 Hong Kong                          106
 Holand-Netherlands                  51
 Panama                              25
FATHER                                1
Name: FATHER, dtype: int64
---- MOTHER ---
 United-States                   160479
 Mexico                            9781
 ?                                 6119
 Puerto-Rico                       2473
 Italy                             1844
 Canada                            1451
 Germany                           1382
 Philippines                       1231
 Poland                            1110
 El-Salvador                       1108
 Cuba                              1108
 Dominican-Republic                1103
 England                            903
 China                              760
 Columbia                           612
 South Korea                        609
 Ireland                            599
 India                              581
 Vietnam                            473
 Japan                              469
 Jamaica                            453
 Guatemala                          444
 Ecuador                            375
 Peru                               355
 Haiti                              353
 Portugal                           342
 Nicaragua                          301
 Hungary                            297
 Greece                             261
 Scotland                           241
 Taiwan                             222
 Honduras                           218
 France                             212
 Iran                               198
 Yugoslavia                         177
 Outlying-U S (Guam USVI etc)       157
 Cambodia                           157
 Laos                               155
 Thailand                           123
 Hong Kong                          107
 Trinadad&Tobago                     99
 Holand-Netherlands                  49
 Panama                              32
Name: MOTHER, dtype: int64
---- SELF ---
 United-States                   176989
 Mexico                            5767
 ?                                 3393
 Puerto-Rico                       1400
 Germany                            851
 Philippines                        845
 Cuba                               837
 Canada                             700
 Dominican-Republic                 690
 El-Salvador                        689
 China                              478
 South Korea                        471
 England                            457
 Columbia                           434
 Italy                              419
 India                              408
 Vietnam                            391
 Poland                             381
 Guatemala                          344
 Japan                              339
 Jamaica                            320
 Peru                               268
 Ecuador                            258
 Haiti                              228
 Nicaragua                          218
 Taiwan                             201
 Portugal                           174
 Iran                               157
 Greece                             147
 Honduras                           144
 Ireland                            135
 France                             121
 Outlying-U S (Guam USVI etc)       119
 Thailand                           113
 Laos                               105
 Hong Kong                          100
 Cambodia                            95
 Hungary                             79
 Scotland                            75
 Trinadad&Tobago                     66
 Yugoslavia                          66
 Panama                              28
 Holand-Netherlands                  23
Name: SELF, dtype: int64
---- PRCITSHP ---

 Native- Born in the United States              176992
 Foreign born- Not a citizen of U S              13401
 Foreign born- U S citizen by naturalization      5855
 Native- Born abroad of American Parent(s)        1756
 Native- Born in Puerto Rico or U S Outlying      1519
Name: PRCITSHP, dtype: int64
---- SEOTR ---
0    180672
2     16153
1      2698
Name: SEOTR, dtype: int64
---- VETQVA ---
 Not in universe    197539
 No                   1593
 Yes                   391
Name: VETQVA, dtype: int64
---- VETYN ---
2    150130
0     47409
1      1984
Name: VETYN, dtype: int64
---- WKSWORK ---
0     95983
52    70314
40     2790
50     2304
26     2268
48     1806
12     1780
30     1378
20     1330
8      1126
36     1108
16      945
32      883
44      845
51      819
24      767
4       757
46      708
35      704
10      694
45      669
6       646
39      602
42      573
28      568
49      509
13      496
1       464
2       458
25      457
3       417
38      380
43      374
22      370
15      353
17      331
5       309
47      278
18      272
14      257
9       239
34      230
7       152
21      135
37      123
41       88
33       81
11       78
27       76
23       67
29       63
31       51
19       48
Name: WKSWORK, dtype: int64
---- YEAR ---
94    99827
95    99696
Name: YEAR, dtype: int64
---- INCOME ---
0    187141
1     12382
Name: INCOME, dtype: int64

In [8]:
#data_name[‘column_name’].replace(0, np.nan, inplace= True)
new_df=census.drop(columns=['MIGMTR1', 'MIGMTR3', 'MIGMTR4','MIGSUN','*(pred)','AGI', 'AHRSPAY'])

In [9]:
new_df.head(5)

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AHSCOL,AMARITL,AMJIND,AMJOCC,ARACE,AREORGN,ASEX,AUNMEM,AUNTYPE,AWKSTAT,CAPGAIN,CAPLOSS,DIVVAL,FEDTAX,GRINGREG,GRINST,HHDFMX,HHDREL,MARSUPWT,MIGSAME,NOEMP,PARENT,FATHER,MOTHER,SELF,PRCITSHP,SEOTR,VETQVA,VETYN,WKSWORK,YEAR,INCOME
0,73,Not in universe,0,0,High school graduate,Not in universe,Widowed,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Other Rel 18+ ever marr not in subfamily,Other relative of householder,1700.09,Not in universe under 1 year old,0,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,0
1,58,Self-employed-not incorporated,4,34,Some college but no degree,Not in universe,Divorced,Construction,Precision production craft & repair,White,All other,Male,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Head of household,South,Arkansas,Householder,Householder,1053.55,No,1,Not in universe,FATHER,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,0
2,18,Not in universe,0,0,10th grade,High school,Never married,Not in universe or children,Not in universe,Asian or Pacific Islander,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Child 18+ never marr Not in a subfamily,Child 18 or older,991.95,Not in universe under 1 year old,0,Not in universe,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,0
3,9,Not in universe,0,0,Children,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1758.14,Yes,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,0
4,10,Not in universe,0,0,Children,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1069.16,Yes,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,0

In [10]:
new_df[['FATHER', 'MOTHER', 'SELF', 'GRINST']] = new_df[['FATHER', 'MOTHER', 'SELF', 'GRINST']].replace(" ?", new_df[['FATHER', 'MOTHER', 'SELF', 'GRINST']].mode())

In [11]:
new_df.columns

Index(['AAGE', 'ACLSWKR', 'ADTIND', 'ADTOCC', 'AHGA', 'AHSCOL', 'AMARITL',
       'AMJIND', 'AMJOCC', 'ARACE', 'AREORGN', 'ASEX', 'AUNMEM', 'AUNTYPE',
       'AWKSTAT', 'CAPGAIN', 'CAPLOSS', 'DIVVAL', 'FEDTAX', 'GRINGREG',
       'GRINST', 'HHDFMX', 'HHDREL', 'MARSUPWT', 'MIGSAME', 'NOEMP', 'PARENT',
       'FATHER', 'MOTHER', 'SELF', 'PRCITSHP', 'SEOTR', 'VETQVA', 'VETYN',
       'WKSWORK', 'YEAR', 'INCOME'],
      dtype='object')

In [12]:
new_df.head(5)

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AHSCOL,AMARITL,AMJIND,AMJOCC,ARACE,AREORGN,ASEX,AUNMEM,AUNTYPE,AWKSTAT,CAPGAIN,CAPLOSS,DIVVAL,FEDTAX,GRINGREG,GRINST,HHDFMX,HHDREL,MARSUPWT,MIGSAME,NOEMP,PARENT,FATHER,MOTHER,SELF,PRCITSHP,SEOTR,VETQVA,VETYN,WKSWORK,YEAR,INCOME
0,73,Not in universe,0,0,High school graduate,Not in universe,Widowed,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Other Rel 18+ ever marr not in subfamily,Other relative of householder,1700.09,Not in universe under 1 year old,0,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,0
1,58,Self-employed-not incorporated,4,34,Some college but no degree,Not in universe,Divorced,Construction,Precision production craft & repair,White,All other,Male,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Head of household,South,Arkansas,Householder,Householder,1053.55,No,1,Not in universe,FATHER,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,0
2,18,Not in universe,0,0,10th grade,High school,Never married,Not in universe or children,Not in universe,Asian or Pacific Islander,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Child 18+ never marr Not in a subfamily,Child 18 or older,991.95,Not in universe under 1 year old,0,Not in universe,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,0
3,9,Not in universe,0,0,Children,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1758.14,Yes,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,0
4,10,Not in universe,0,0,Children,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1069.16,Yes,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,0

In [13]:
for c in new_df.columns:
    print("---- %s ---" % c)
    print(new_df[c].value_counts())

---- AAGE ---
34    3489
35    3450
36    3353
31    3351
33    3340
5     3332
4     3318
3     3279
37    3278
38    3277
2     3236
7     3218
30    3203
32    3188
8     3187
6     3171
9     3162
13    3152
39    3144
1     3138
41    3134
10    3134
11    3128
40    3114
14    3068
12    3060
29    3050
28    3013
42    2995
15    2926
      ...
60    1560
65    1550
62    1531
63    1501
61    1497
67    1496
66    1443
68    1436
71    1418
69    1412
70    1410
73    1354
72    1315
74    1227
75    1065
76    1050
77     979
78     876
79     811
80     799
90     725
81     720
82     615
83     561
84     519
85     423
86     348
87     301
88     241
89     195
Name: AAGE, Length: 91, dtype: int64
---- ACLSWKR ---
 Not in universe                   100245
 Private                            72028
 Self-employed-not incorporated      8445
 Local government                    7784
 State government                    4227
 Self-employed-incorporated          3265
 Federal government                  2925
 Never worked                         439
 Without pay                          165
Name: ACLSWKR, dtype: int64
---- ADTIND ---
0     100684
33     17070
43      8283
4       5984
42      4683
45      4482
29      4209
37      4022
41      3964
32      3596
35      3380
39      2937
34      2765
44      2549
2       2196
11      1764
50      1704
40      1651
47      1644
38      1629
24      1503
12      1350
19      1346
30      1181
31      1178
25      1084
9        993
22       952
36       945
13       899
1        827
48       652
27       626
49       610
3        563
21       559
6        554
5        553
8        550
16       539
23       525
18       483
15       452
7        422
14       295
46       187
17       157
28       143
26       127
51        36
20        32
10         4
Name: ADTIND, dtype: int64
---- ADTOCC ---
0     100684
2       8756
26      7887
19      5413
29      5105
36      4145
34      4025
10      3683
16      3445
23      3392
12      3340
33      3325
3       3195
35      3168
38      3003
31      2699
32      2398
37      2234
8       2151
42      1918
30      1897
24      1847
17      1771
28      1661
44      1592
41      1592
43      1382
4       1364
13      1271
18      1083
39      1017
14       932
5        855
15       815
27       780
25       767
9        738
7        731
11       637
40       617
1        544
21       533
6        441
22       411
45       172
20        71
46        36
Name: ADTOCC, dtype: int64
---- AHGA ---
 High school graduate                      48407
 Children                                  47422
 Some college but no degree                27820
 Bachelors degree(BA AB BS)                19865
 7th and 8th grade                          8007
 10th grade                                 7557
 11th grade                                 6876
 Masters degree(MA MS MEng MEd MSW MBA)     6541
 9th grade                                  6230
 Associates degree-occup /vocational        5358
 Associates degree-academic program         4363
 5th or 6th grade                           3277
 12th grade no diploma                      2126
 1st 2nd 3rd or 4th grade                   1799
 Prof school degree (MD DDS DVM LLB JD)     1793
 Doctorate degree(PhD EdD)                  1263
 Less than 1st grade                         819
Name: AHGA, dtype: int64
---- AHSCOL ---
 Not in universe          186943
 High school                6892
 College or university      5688
Name: AHSCOL, dtype: int64
---- AMARITL ---
 Never married                      86485
 Married-civilian spouse present    84222
 Divorced                           12710
 Widowed                            10463
 Separated                           3460
 Married-spouse absent               1518
 Married-A F spouse present           665
Name: AMARITL, dtype: int64
---- AMJIND ---
 Not in universe or children            100684
 Retail trade                            17070
 Manufacturing-durable goods              9015
 Education                                8283
 Manufacturing-nondurable goods           6897
 Finance insurance and real estate        6145
 Construction                             5984
 Business and repair services             5651
 Medical except hospital                  4683
 Public administration                    4610
 Other professional services              4482
 Transportation                           4209
 Hospital services                        3964
 Wholesale trade                          3596
 Agriculture                              3023
 Personal services except private HH      2937
 Social services                          2549
 Entertainment                            1651
 Communications                           1181
 Utilities and sanitary services          1178
 Private household services                945
 Mining                                    563
 Forestry and fisheries                    187
 Armed Forces                               36
Name: AMJIND, dtype: int64
---- AMJOCC ---
 Not in universe                          100684
 Adm support including clerical            14837
 Professional specialty                    13940
 Executive admin and managerial            12495
 Other service                             12099
 Sales                                     11783
 Precision production craft & repair       10518
 Machine operators assmblrs & inspctrs      6379
 Handlers equip cleaners etc                4127
 Transportation and material moving         4020
 Farming forestry and fishing               3146
 Technicians and related support            3018
 Protective services                        1661
 Private household services                  780
 Armed Forces                                 36
Name: AMJOCC, dtype: int64
---- ARACE ---
 White                          167365
 Black                           20415
 Asian or Pacific Islander        5835
 Other                            3657
 Amer Indian Aleut or Eskimo      2251
Name: ARACE, dtype: int64
---- AREORGN ---
 All other                    171907
 Mexican-American               8079
 Mexican (Mexicano)             7234
 Central or South American      3895
 Puerto Rican                   3313
 Other Spanish                  2485
 Cuban                          1126
 NA                              874
 Do not know                     306
 Chicano                         304
Name: AREORGN, dtype: int64
---- ASEX ---
 Female    103984
 Male       95539
Name: ASEX, dtype: int64
---- AUNMEM ---
 Not in universe    180459
 No                  16034
 Yes                  3030
Name: AUNMEM, dtype: int64
---- AUNTYPE ---
 Not in universe          193453
 Other job loser            2038
 Re-entrant                 2019
 Job loser - on layoff       976
 Job leaver                  598
 New entrant                 439
Name: AUNTYPE, dtype: int64
---- AWKSTAT ---
 Children or Armed Forces              123769
 Full-time schedules                    40736
 Not in labor force                     26808
 PT for non-econ reasons usually FT      3322
 Unemployed full-time                    2311
 PT for econ reasons usually PT          1209
 Unemployed part- time                    843
 PT for econ reasons usually FT           525
Name: AWKSTAT, dtype: int64
---- CAPGAIN ---
0        192144
15024       788
7688        609
7298        582
99999       390
3103        237
5178        207
5013        158
4386        151
3325        121
8614        118
10520        98
27828        94
4650         93
20051        91
594          88
4064         83
2174         83
1086         81
14084        77
1409         77
13550        74
2829         71
10605        70
9386         70
1055         69
3464         67
2329         66
6849         65
2964         65
          ...
2961         14
18481        14
10566        13
2036         11
15020        11
34095        11
114          11
9562         10
1831          9
4687          9
5721          9
1731          5
7262          5
5060          5
6360          4
2098          4
1111          4
3800          3
22040         2
2774          2
1090          2
41310         2
6612          1
9472          1
8530          1
2227          1
4594          1
2387          1
1140          1
2601          1
Name: CAPGAIN, Length: 132, dtype: int64
---- CAPLOSS ---
0       195617
1902       407
1977       381
1887       364
1602       193
2415       122
1485        95
1848        88
1876        87
1672        85
1590        84
1740        72
2339        61
1564        60
1980        59
1741        58
1408        56
1719        56
2001        56
2258        56
1669        55
1974        51
2002        51
2377        48
2205        46
1579        43
1721        42
1668        39
2051        38
2559        38
         ...
1594         8
2238         7
2788         7
1380         7
2282         7
653          7
2090         6
810          5
2465         5
772          5
3770         5
1021         4
2472         4
4608         4
1755         4
1138         4
3683         4
2597         3
2722         3
2754         3
2027         2
2201         2
1640         2
1956         2
3900         2
974          2
155          1
2080         1
2519         1
1911         1
Name: CAPLOSS, Length: 113, dtype: int64
---- DIVVAL ---
0        178382
100        1148
500        1030
1000        894
200         866
50          832
2000        574
250         555
150         549
300         523
1           472
400         409
1500        380
2500        372
25          360
5000        304
3000        292
600         287
10          253
4000        222
20          213
2           193
10000       182
5           179
125         175
75          169
750         164
30          163
12          146
60          142
          ...
667           1
358           1
1895          1
9119          1
3098          1
47558         1
2640          1
5349          1
593           1
2205          1
284           1
4382          1
8600          1
999           1
2104          1
796           1
1361          1
26000         1
1948          1
7506          1
4197          1
541           1
2844          1
2022          1
998           1
568           1
1309          1
21100         1
5663          1
5024          1
Name: DIVVAL, Length: 1478, dtype: int64
---- FEDTAX ---
 Nonfiler                        75094
 Joint both under 65             67383
 Single                          37421
 Joint both 65+                   8332
 Head of household                7426
 Joint one under 65 & one 65+     3867
Name: FEDTAX, dtype: int64
---- GRINGREG ---
 Not in universe    183750
 South                4889
 West                 4074
 Midwest              3575
 Northeast            2705
 Abroad                530
Name: GRINGREG, dtype: int64
---- GRINST ---

 Not in universe         184458
 California                1714
 Utah                      1063
 Florida                    849
 North Carolina             812
 Abroad                     671
 Oklahoma                   626
 Minnesota                  576
 Indiana                    533
 North Dakota               499
 New Mexico                 463
 Michigan                   441
 Alaska                     290
 Kentucky                   244
 Arizona                    243
 New Hampshire              242
 Wyoming                    241
 Colorado                   239
 Oregon                     236
 West Virginia              231
 Georgia                    227
 Montana                    226
 Alabama                    216
 Ohio                       211
 Texas                      209
 Arkansas                   205
 Mississippi                204
 Tennessee                  202
 Pennsylvania               199
 New York                   195
 Louisiana                  192
 Vermont                    191
 Iowa                       189
 Illinois                   180
 Nebraska                   178
 Missouri                   175
 Nevada                     174
 Maine                      167
 Massachusetts              151
 Kansas                     149
 South Dakota               138
 Maryland                   136
 Virginia                   126
 Connecticut                117
 District of Columbia       116
 Wisconsin                  105
 South Carolina              95
 New Jersey                  75
 Delaware                    73
 Idaho                       31
Name: GRINST, dtype: int64
---- HHDFMX ---
 Householder                                        53248
 Child <18 never marr not in subfamily              50326
 Spouse of householder                              41695
 Nonfamily householder                              22213
 Child 18+ never marr Not in a subfamily            12030
 Secondary individual                                6122
 Other Rel 18+ ever marr not in subfamily            1956
 Grandchild <18 never marr child of subfamily RP     1868
 Other Rel 18+ never marr not in subfamily           1728
 Grandchild <18 never marr not in subfamily          1066
 Child 18+ ever marr Not in a subfamily              1013
 Child under 18 of RP of unrel subfamily              732
 RP of unrelated subfamily                            685
 Child 18+ ever marr RP of subfamily                  671
 Other Rel <18 never marr child of subfamily RP       656
 Other Rel 18+ ever marr RP of subfamily              656
 Other Rel 18+ spouse of subfamily RP                 638
 Child 18+ never marr RP of subfamily                 589
 Other Rel <18 never marr not in subfamily            584
 Grandchild 18+ never marr not in subfamily           375
 In group quarters                                    196
 Child 18+ spouse of subfamily RP                     126
 Other Rel 18+ never marr RP of subfamily              94
 Child <18 never marr RP of subfamily                  80
 Spouse of RP of unrelated subfamily                   52
 Child <18 ever marr not in subfamily                  36
 Grandchild 18+ ever marr not in subfamily             34
 Grandchild 18+ spouse of subfamily RP                 10
 Child <18 ever marr RP of subfamily                    9
 Grandchild 18+ ever marr RP of subfamily               9
 Other Rel <18 ever marr RP of subfamily                6
 Grandchild 18+ never marr RP of subfamily              6
 Other Rel <18 never married RP of subfamily            4
 Other Rel <18 spouse of subfamily RP                   3
 Child <18 spouse of subfamily RP                       2
 Grandchild <18 never marr RP of subfamily              2
 Grandchild <18 ever marr not in subfamily              2
 Other Rel <18 ever marr not in subfamily               1
Name: HHDFMX, dtype: int64
---- HHDREL ---
 Householder                             75475
 Child under 18 never married            50426
 Spouse of householder                   41709
 Child 18 or older                       14430
 Other relative of householder            9703
 Nonrelative of householder               7601
 Group Quarters- Secondary individual      132
 Child under 18 ever married                47
Name: HHDREL, dtype: int64
---- MARSUPWT ---
1601.40    32
753.23     32
1191.21    32
1787.34    32
707.90     31
1317.51    31
1070.15    30
1839.19    28
1002.02    28
1009.39    28
1033.83    28
1029.73    27
1122.60    27
1528.84    27
964.50     26
1244.66    26
1011.71    26
1155.20    26
988.79     26
1882.96    26
974.01     26
1218.82    26
1138.19    25
1739.89    25
1032.82    25
1888.13    25
1224.90    25
1184.69    25
1022.93    24
812.13     24
           ..
2298.47     1
1128.55     1
1947.22     1
809.41      1
1160.64     1
810.59      1
843.23      1
2081.13     1
1816.23     1
1591.24     1
744.67      1
2840.59     1
1106.60     1
2051.77     1
2758.66     1
5358.66     1
2563.43     1
814.29      1
1648.00     1
453.09      1
558.09      1
958.97      1
2342.01     1
2227.15     1
2032.31     1
1043.52     1
1967.15     1
790.20      1
1052.48     1
384.00      1
Name: MARSUPWT, Length: 99800, dtype: int64
---- MIGSAME ---
 Not in universe under 1 year old    101212
 Yes                                  82538
 No                                   15773
Name: MIGSAME, dtype: int64
---- NOEMP ---
0    95983
6    36511
1    23109
4    14379
3    13425
2    10081
5     6035
Name: NOEMP, dtype: int64
---- PARENT ---
 Not in universe           144232
 Both parents present       38983
 Mother only present        12772
 Father only present         1883
 Neither parent present      1653
Name: PARENT, dtype: int64
---- FATHER ---
 United-States                   165875
 Mexico                           10008
 Puerto-Rico                       2680
 Italy                             2212
 Canada                            1380
 Germany                           1356
 Dominican-Republic                1290
 Poland                            1212
 Philippines                       1154
 Cuba                              1125
 El-Salvador                        982
 China                              856
 England                            793
 Columbia                           614
 India                              580
 South Korea                        530
 Ireland                            508
 Jamaica                            463
 Vietnam                            457
 Guatemala                          445
 Japan                              392
 Portugal                           388
 Ecuador                            379
 Haiti                              351
 Greece                             344
 Peru                               335
 Nicaragua                          315
 Hungary                            306
 Scotland                           247
 Iran                               233
 Yugoslavia                         217
 Taiwan                             199
 Cambodia                           196
 Honduras                           194
 France                             191
 Outlying-U S (Guam USVI etc)       159
 Laos                               154
 Trinadad&Tobago                    113
 Thailand                           107
 Hong Kong                          106
 Holand-Netherlands                  51
 Panama                              25
FATHER                                1
Name: FATHER, dtype: int64
---- MOTHER ---
 United-States                   166598
 Mexico                            9781
 Puerto-Rico                       2473
 Italy                             1844
 Canada                            1451
 Germany                           1382
 Philippines                       1231
 Poland                            1110
 El-Salvador                       1108
 Cuba                              1108
 Dominican-Republic                1103
 England                            903
 China                              760
 Columbia                           612
 South Korea                        609
 Ireland                            599
 India                              581
 Vietnam                            473
 Japan                              469
 Jamaica                            453
 Guatemala                          444
 Ecuador                            375
 Peru                               355
 Haiti                              353
 Portugal                           342
 Nicaragua                          301
 Hungary                            297
 Greece                             261
 Scotland                           241
 Taiwan                             222
 Honduras                           218
 France                             212
 Iran                               198
 Yugoslavia                         177
 Cambodia                           157
 Outlying-U S (Guam USVI etc)       157
 Laos                               155
 Thailand                           123
 Hong Kong                          107
 Trinadad&Tobago                     99
 Holand-Netherlands                  49
 Panama                              32
Name: MOTHER, dtype: int64
---- SELF ---
 United-States                   180382
 Mexico                            5767
 Puerto-Rico                       1400
 Germany                            851
 Philippines                        845
 Cuba                               837
 Canada                             700
 Dominican-Republic                 690
 El-Salvador                        689
 China                              478
 South Korea                        471
 England                            457
 Columbia                           434
 Italy                              419
 India                              408
 Vietnam                            391
 Poland                             381
 Guatemala                          344
 Japan                              339
 Jamaica                            320
 Peru                               268
 Ecuador                            258
 Haiti                              228
 Nicaragua                          218
 Taiwan                             201
 Portugal                           174
 Iran                               157
 Greece                             147
 Honduras                           144
 Ireland                            135
 France                             121
 Outlying-U S (Guam USVI etc)       119
 Thailand                           113
 Laos                               105
 Hong Kong                          100
 Cambodia                            95
 Hungary                             79
 Scotland                            75
 Trinadad&Tobago                     66
 Yugoslavia                          66
 Panama                              28
 Holand-Netherlands                  23
Name: SELF, dtype: int64
---- PRCITSHP ---
 Native- Born in the United States              176992
 Foreign born- Not a citizen of U S              13401
 Foreign born- U S citizen by naturalization      5855
 Native- Born abroad of American Parent(s)        1756
 Native- Born in Puerto Rico or U S Outlying      1519
Name: PRCITSHP, dtype: int64
---- SEOTR ---
0    180672
2     16153
1      2698
Name: SEOTR, dtype: int64
---- VETQVA ---
 Not in universe    197539
 No                   1593
 Yes                   391
Name: VETQVA, dtype: int64
---- VETYN ---
2    150130
0     47409
1      1984
Name: VETYN, dtype: int64
---- WKSWORK ---
0     95983
52    70314
40     2790
50     2304
26     2268
48     1806
12     1780
30     1378
20     1330
8      1126
36     1108
16      945
32      883
44      845
51      819
24      767
4       757
46      708
35      704
10      694
45      669
6       646
39      602
42      573
28      568
49      509
13      496
1       464
2       458
25      457
3       417
38      380
43      374
22      370
15      353
17      331
5       309
47      278
18      272
14      257
9       239
34      230
7       152
21      135
37      123
41       88
33       81
11       78
27       76
23       67
29       63
31       51
19       48
Name: WKSWORK, dtype: int64
---- YEAR ---
94    99827
95    99696
Name: YEAR, dtype: int64
---- INCOME ---
0    187141
1     12382
Name: INCOME, dtype: int64

In [14]:
#new_df.to_csv(r'census_mode_fitted.csv')
new_df.isna().sum()

AAGE        0
ACLSWKR     0
ADTIND      0
ADTOCC      0
AHGA        0
AHSCOL      0
AMARITL     0
AMJIND      0
AMJOCC      0
ARACE       0
AREORGN     0
ASEX        0
AUNMEM      0
AUNTYPE     0
AWKSTAT     0
CAPGAIN     0
CAPLOSS     0
DIVVAL      0
FEDTAX      0
GRINGREG    0
GRINST      0
HHDFMX      0
HHDREL      0
MARSUPWT    0
MIGSAME     0
NOEMP       0
PARENT      0
FATHER      0
MOTHER      0
SELF        0
PRCITSHP    0
SEOTR       0
VETQVA      0
VETYN       0
WKSWORK     0
YEAR        0
INCOME      0
dtype: int64

In [15]:
new_df=pd.get_dummies(new_df, columns=['AAGE', 'ACLSWKR', 'AHGA', 'AHSCOL', 'AMARITL',
       'AMJIND', 'AMJOCC', 'ARACE', 'AREORGN', 'ASEX', 'AUNMEM', 'AUNTYPE',
       'AWKSTAT','FEDTAX', 'GRINGREG',
       'GRINST', 'HHDFMX', 'HHDREL', 'MIGSAME', 'PARENT',
       'FATHER', 'MOTHER', 'SELF', 'PRCITSHP', 'VETQVA'])

In [16]:
list_columns = new_df.columns.tolist()

In [17]:
list_columns.remove("INCOME")
features = list_columns
target = ["INCOME"]

In [18]:
new_df.shape

(199523, 463)

In [19]:
X=new_df[features]
Y=new_df[target]

In [20]:
X.head(5)

,ADTIND,ADTOCC,CAPGAIN,CAPLOSS,DIVVAL,MARSUPWT,NOEMP,SEOTR,VETYN,WKSWORK,YEAR,AAGE_0,AAGE_1,AAGE_2,AAGE_3,AAGE_4,AAGE_5,AAGE_6,AAGE_7,AAGE_8,AAGE_9,AAGE_10,AAGE_11,AAGE_12,AAGE_13,AAGE_14,AAGE_15,AAGE_16,AAGE_17,AAGE_18,AAGE_19,AAGE_20,AAGE_21,AAGE_22,AAGE_23,AAGE_24,AAGE_25,AAGE_26,AAGE_27,AAGE_28,AAGE_29,AAGE_30,AAGE_31,AAGE_32,AAGE_33,AAGE_34,AAGE_35,AAGE_36,AAGE_37,AAGE_38,AAGE_39,AAGE_40,AAGE_41,AAGE_42,AAGE_43,AAGE_44,AAGE_45,AAGE_46,AAGE_47,AAGE_48,AAGE_49,AAGE_50,AAGE_51,AAGE_52,AAGE_53,AAGE_54,AAGE_55,AAGE_56,AAGE_57,AAGE_58,AAGE_59,AAGE_60,AAGE_61,AAGE_62,AAGE_63,AAGE_64,AAGE_65,AAGE_66,AAGE_67,AAGE_68,AAGE_69,AAGE_70,AAGE_71,AAGE_72,AAGE_73,AAGE_74,AAGE_75,AAGE_76,AAGE_77,AAGE_78,AAGE_79,AAGE_80,AAGE_81,AAGE_82,AAGE_83,AAGE_84,AAGE_85,AAGE_86,AAGE_87,AAGE_88,AAGE_89,AAGE_90,ACLSWKR_ Federal government,ACLSWKR_ Local government,ACLSWKR_ Never worked,ACLSWKR_ Not in universe,ACLSWKR_ Private,ACLSWKR_ Self-employed-incorporated,ACLSWKR_ Self-employed-not incorporated,ACLSWKR_ State government,ACLSWKR_ Without pay,AHGA_ 10th grade,AHGA_ 11th grade,AHGA_ 12th grade no diploma,AHGA_ 1st 2nd 3rd or 4th grade,AHGA_ 5th or 6th grade,AHGA_ 7th and 8th grade,AHGA_ 9th grade,AHGA_ Associates degree-academic program,AHGA_ Associates degree-occup /vocational,AHGA_ Bachelors degree(BA AB BS),AHGA_ Children,AHGA_ Doctorate degree(PhD EdD),AHGA_ High school graduate,AHGA_ Less than 1st grade,AHGA_ Masters degree(MA MS MEng MEd MSW MBA),AHGA_ Prof school degree (MD DDS DVM LLB JD),AHGA_ Some college but no degree,AHSCOL_ College or university,AHSCOL_ High school,AHSCOL_ Not in universe,AMARITL_ Divorced,AMARITL_ Married-A F spouse present,AMARITL_ Married-civilian spouse present,AMARITL_ Married-spouse absent,AMARITL_ Never married,AMARITL_ Separated,AMARITL_ Widowed,AMJIND_ Agriculture,AMJIND_ Armed Forces,AMJIND_ Business and repair services,AMJIND_ Communications,AMJIND_ Construction,AMJIND_ Education,AMJIND_ Entertainment,AMJIND_ Finance insurance and real estate,AMJIND_ Forestry and fisheries,AMJIND_ Hospital services,AMJIND_ Manufacturing-durable goods,AMJIND_ Manufacturing-nondurable goods,AMJIND_ Medical except hospital,AMJIND_ Mining,AMJIND_ Not in universe or children,AMJIND_ Other professional services,AMJIND_ Personal services except private HH,AMJIND_ Private household services,AMJIND_ Public administration,AMJIND_ Retail trade,AMJIND_ Social services,AMJIND_ Transportation,AMJIND_ Utilities and sanitary services,AMJIND_ Wholesale trade,AMJOCC_ Adm support including clerical,AMJOCC_ Armed Forces,AMJOCC_ Executive admin and managerial,AMJOCC_ Farming forestry and fishing,AMJOCC_ Handlers equip cleaners etc,AMJOCC_ Machine operators assmblrs & inspctrs,AMJOCC_ Not in universe,AMJOCC_ Other service,AMJOCC_ Precision production craft & repair,AMJOCC_ Private household services,AMJOCC_ Professional specialty,AMJOCC_ Protective services,AMJOCC_ Sales,AMJOCC_ Technicians and related support,AMJOCC_ Transportation and material moving,ARACE_ Amer Indian Aleut or Eskimo,ARACE_ Asian or Pacific Islander,ARACE_ Black,ARACE_ Other,ARACE_ White,AREORGN_ All other,AREORGN_ Central or South American,AREORGN_ Chicano,AREORGN_ Cuban,AREORGN_ Do not know,AREORGN_ Mexican (Mexicano),AREORGN_ Mexican-American,AREORGN_ NA,AREORGN_ Other Spanish,AREORGN_ Puerto Rican,ASEX_ Female,ASEX_ Male,AUNMEM_ No,AUNMEM_ Not in universe,AUNMEM_ Yes,AUNTYPE_ Job leaver,AUNTYPE_ Job loser - on layoff,AUNTYPE_ New entrant,AUNTYPE_ Not in universe,AUNTYPE_ Other job loser,AUNTYPE_ Re-entrant,AWKSTAT_ Children or Armed Forces,AWKSTAT_ Full-time schedules,AWKSTAT_ Not in labor force,AWKSTAT_ PT for econ reasons usually FT,AWKSTAT_ PT for econ reasons usually PT,AWKSTAT_ PT for non-econ reasons usually FT,AWKSTAT_ Unemployed full-time,AWKSTAT_ Unemployed part- time,FEDTAX_ Head of household,FEDTAX_ Joint both 65+,FEDTAX_ Joint both under 65,FEDTAX_ Joint one under 65 & one 65+,FEDTAX_ Nonfiler,FEDTAX_ Single,GRINGREG_ Abroad,GRINGREG_ Midwest,GRINGREG_ Northeast,GRINGREG_ Not in universe,GRINGREG_ South,GRINGREG_ West,GRINST_ Abroad,GRINST_ Alabama,GRINST_ Alaska,GRINST_ Arizona,GRINST_ Arkansas,GRINST_ California,GRINST_ Colorado,GRINST_ Connecticut,GRINST_ Delaware,GRINST_ District of Columbia,GRINST_ Florida,GRINST_ Georgia,GRINST_ Idaho,GRINST_ Illinois,GRINST_ Indiana,GRINST_ Iowa,GRINST_ Kansas,GRINST_ Kentucky,GRINST_ Louisiana,GRINST_ Maine,GRINST_ Maryland,GRINST_ Massachusetts,GRINST_ Michigan,GRINST_ Minnesota,GRINST_ Mississippi,GRINST_ Missouri,GRINST_ Montana,GRINST_ Nebraska,GRINST_ Nevada,GRINST_ New Hampshire,GRINST_ New Jersey,GRINST_ New Mexico,GRINST_ New York,GRINST_ North Carolina,GRINST_ North Dakota,GRINST_ Not in universe,GRINST_ Ohio,GRINST_ Oklahoma,GRINST_ Oregon,GRINST_ Pennsylvania,GRINST_ South Carolina,GRINST_ South Dakota,GRINST_ Tennessee,GRINST_ Texas,GRINST_ Utah,GRINST_ Vermont,GRINST_ Virginia,GRINST_ West Virginia,GRINST_ Wisconsin,GRINST_ Wyoming,HHDFMX_ Child 18+ ever marr Not in a subfamily,HHDFMX_ Child 18+ ever marr RP of subfamily,HHDFMX_ Child 18+ never marr Not in a subfamily,HHDFMX_ Child 18+ never marr RP of subfamily,HHDFMX_ Child 18+ spouse of subfamily RP,HHDFMX_ Child <18 ever marr RP of subfamily,HHDFMX_ Child <18 ever marr not in subfamily,HHDFMX_ Child <18 never marr RP of subfamily,HHDFMX_ Child <18 never marr not in subfamily,HHDFMX_ Child <18 spouse of subfamily RP,HHDFMX_ Child under 18 of RP of unrel subfamily,HHDFMX_ Grandchild 18+ ever marr RP of subfamily,HHDFMX_ Grandchild 18+ ever marr not in subfamily,HHDFMX_ Grandchild 18+ never marr RP of subfamily,HHDFMX_ Grandchild 18+ never marr not in subfamily,HHDFMX_ Grandchild 18+ spouse of subfamily RP,HHDFMX_ Grandchild <18 ever marr not in subfamily,HHDFMX_ Grandchild <18 never marr RP of subfamily,HHDFMX_ Grandchild <18 never marr child of subfamily RP,HHDFMX_ Grandchild <18 never marr not in subfamily,HHDFMX_ Householder,HHDFMX_ In group quarters,HHDFMX_ Nonfamily householder,HHDFMX_ Other Rel 18+ ever marr RP of subfamily,HHDFMX_ Other Rel 18+ ever marr not in subfamily,HHDFMX_ Other Rel 18+ never marr RP of subfamily,HHDFMX_ Other Rel 18+ never marr not in subfamily,HHDFMX_ Other Rel 18+ spouse of subfamily RP,HHDFMX_ Other Rel <18 ever marr RP of subfamily,HHDFMX_ Other Rel <18 ever marr not in subfamily,HHDFMX_ Other Rel <18 never marr child of subfamily RP,HHDFMX_ Other Rel <18 never marr not in subfamily,HHDFMX_ Other Rel <18 never married RP of subfamily,HHDFMX_ Other Rel <18 spouse of subfamily RP,HHDFMX_ RP of unrelated subfamily,HHDFMX_ Secondary individual,HHDFMX_ Spouse of RP of unrelated subfamily,HHDFMX_ Spouse of householder,HHDREL_ Child 18 or older,HHDREL_ Child under 18 ever married,HHDREL_ Child under 18 never married,HHDREL_ Group Quarters- Secondary individual,HHDREL_ Householder,HHDREL_ Nonrelative of householder,HHDREL_ Other relative of householder,HHDREL_ Spouse of householder,MIGSAME_ No,MIGSAME_ Not in universe under 1 year old,MIGSAME_ Yes,PARENT_ Both parents present,PARENT_ Father only present,PARENT_ Mother only present,PARENT_ Neither parent present,PARENT_ Not in universe,FATHER_ Cambodia,FATHER_ Canada,FATHER_ China,FATHER_ Columbia,FATHER_ Cuba,FATHER_ Dominican-Republic,FATHER_ Ecuador,FATHER_ El-Salvador,FATHER_ England,FATHER_ France,FATHER_ Germany,FATHER_ Greece,FATHER_ Guatemala,FATHER_ Haiti,FATHER_ Holand-Netherlands,FATHER_ Honduras,FATHER_ Hong Kong,FATHER_ Hungary,FATHER_ India,FATHER_ Iran,FATHER_ Ireland,FATHER_ Italy,FATHER_ Jamaica,FATHER_ Japan,FATHER_ Laos,FATHER_ Mexico,FATHER_ Nicaragua,FATHER_ Outlying-U S (Guam USVI etc),FATHER_ Panama,FATHER_ Peru,FATHER_ Philippines,FATHER_ Poland,FATHER_ Portugal,FATHER_ Puerto-Rico,FATHER_ Scotland,FATHER_ South Korea,FATHER_ Taiwan,FATHER_ Thailand,FATHER_ Trinadad&Tobago,FATHER_ United-States,FATHER_ Vietnam,FATHER_ Yugoslavia,FATHER_FATHER,MOTHER_ Cambodia,MOTHER_ Canada,MOTHER_ China,MOTHER_ Columbia,MOTHER_ Cuba,MOTHER_ Dominican-Republic,MOTHER_ Ecuador,MOTHER_ El-Salvador,MOTHER_ England,MOTHER_ France,MOTHER_ Germany,MOTHER_ Greece,MOTHER_ Guatemala,MOTHER_ Haiti,MOTHER_ Holand-Netherlands,MOTHER_ Honduras,MOTHER_ Hong Kong,MOTHER_ Hungary,MOTHER_ India,MOTHER_ Iran,MOTHER_ Ireland,MOTHER_ Italy,MOTHER_ Jamaica,MOTHER_ Japan,MOTHER_ Laos,MOTHER_ Mexico,MOTHER_ Nicaragua,MOTHER_ Outlying-U S (Guam USVI etc),MOTHER_ Panama,MOTHER_ Peru,MOTHER_ Philippines,MOTHER_ Poland,MOTHER_ Portugal,MOTHER_ Puerto-Rico,MOTHER_ Scotland,MOTHER_ South Korea,MOTHER_ Taiwan,MOTHER_ Thailand,MOTHER_ Trinadad&Tobago,MOTHER_ United-States,MOTHER_ Vietnam,MOTHER_ Yugoslavia,SELF_ Cambodia,SELF_ Canada,SELF_ China,SELF_ Columbia,SELF_ Cuba,SELF_ Dominican-Republic,SELF_ Ecuador,SELF_ El-Salvador,SELF_ England,SELF_ France,SELF_ Germany,SELF_ Greece,SELF_ Guatemala,SELF_ Haiti,SELF_ Holand-Netherlands,SELF_ Honduras,SELF_ Hong Kong,SELF_ Hungary,SELF_ India,SELF_ Iran,SELF_ Ireland,SELF_ Italy,SELF_ Jamaica,SELF_ Japan,SELF_ Laos,SELF_ Mexico,SELF_ Nicaragua,SELF_ Outlying-U S (Guam USVI etc),SELF_ Panama,SELF_ Peru,SELF_ Philippines,SELF_ Poland,SELF_ Portugal,SELF_ Puerto-Rico,SELF_ Scotland,SELF_ South Korea,SELF_ Taiwan,SELF_ Thailand,SELF_ Trinadad&Tobago,SELF_ United-States,SELF_ Vietnam,SELF_ Yugoslavia,PRCITSHP_ Foreign born- Not a citizen of U S,PRCITSHP_ Foreign born- U S citizen by naturalization,PRCITSHP_ Native- Born abroad of American Parent(s),PRCITSHP_ Native- Born in Puerto Rico or U S Outlying,PRCITSHP_ Native- Born in the United States,VETQVA_ No,VETQVA_ Not in universe,VETQVA_ Yes
0,0,0,0,0,0,1700.09,0,0,2,0,95,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0
1,4,34,0,0,0,1053.55,1,0,2,52,94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0
2,0,0,0,0,0,991.95,0,0,2,0,95,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0
3,0,0,0,0,0,1758.14,0,0,0,0,94,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0
4,0,0,0,0,0,1069.16,0,0,0,0,94,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0

In [21]:
Y.head(5)

   INCOME
0       0
1       0
2       0
3       0
4       0

In [22]:
X_train, X_test, Y_train, Y_test=train_test_split( X, Y, test_size=0.33,random_state=23)

In [23]:
X_train.shape
X_test.shape

(133680, 462)

(65843, 462)

## Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression
regressor=LogisticRegression()

In [25]:
regressor.fit(X_train, Y_train.values.ravel())

C:\Users\suraj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [26]:
regressor.coef_

array([[-9.71108141e-03, -4.57582910e-02,  1.01035356e-04,
         6.07210841e-04,  1.82552811e-04,  4.57498648e-05,
         1.70106247e-01, -2.52214041e-02,  2.80561999e-01,
         3.29477334e-02, -6.65162090e-02, -2.09846921e-02,
        -2.42319631e-02, -2.52490582e-02, -2.56888471e-02,
        -2.50268131e-02, -2.51979232e-02, -2.39800156e-02,
        -2.48485546e-02, -2.50022045e-02, -2.45742283e-02,
        -2.36880827e-02, -2.44813890e-02, -2.31769873e-02,
        -2.43385899e-02, -2.30433183e-02, -5.99760878e-02,
        -2.10889348e-02, -7.98291471e-02, -1.57551589e-01,
        -1.36854004e-01, -1.30766602e-01, -3.48076583e-01,
        -2.89153011e-01, -7.45618085e-01, -7.99076444e-01,
        -8.67106474e-01, -9.10805978e-01, -9.39920515e-01,
        -6.89167554e-01, -7.63524322e-01, -4.30242302e-01,
        -2.37007770e-01, -2.78562817e-01, -2.19536748e-01,
        -4.99777685e-02,  3.40998716e-02,  5.41921926e-03,
         1.56446375e-01,  1.35901048e-01,  3.40678524e-02,
         8.09212906e-02,  1.11041648e-01,  2.11443565e-01,
         1.22862190e-01,  1.30637862e-01,  2.32600984e-01,
         4.36280647e-01,  4.05076115e-01,  4.59330521e-01,
         2.49502837e-01,  4.10831603e-01,  4.99688418e-01,
         5.30225673e-01,  3.89567802e-01,  4.62745405e-01,
         6.36308573e-01,  1.98477892e-01,  2.96246627e-01,
         4.20220709e-01,  2.95105349e-01,  1.95446014e-01,
         1.60928824e-01,  3.37009204e-01,  9.41661845e-03,
         1.84885774e-01,  2.67336331e-02, -1.25958715e-02,
         1.56514325e-01, -4.72430247e-02,  2.11924979e-01,
         4.73825554e-02,  3.57318153e-02, -1.43773899e-01,
         4.54584944e-02, -1.06858839e-01,  2.11875713e-01,
         1.71106980e-01,  5.09998932e-02,  5.77579653e-02,
         6.24367283e-02, -4.93301328e-02, -1.34872988e-02,
        -1.02651545e-01,  5.20657197e-02, -3.97746056e-02,
         4.04020039e-03,  1.43150653e-02,  6.47796050e-03,
         4.56312390e-03,  5.33829721e-03,  3.74398070e-02,
         1.81986047e-01, -3.63020333e-01,  4.38362148e-02,
        -3.94420425e-01,  6.42808723e-02,  8.95209280e-01,
         2.24353212e-01, -5.91360907e-01, -5.90348136e-02,
        -9.43697639e-01, -8.55975852e-01, -3.31331917e-01,
        -2.31964368e-01, -5.77795338e-01, -9.38946795e-01,
        -8.03908171e-01,  5.52451638e-02, -1.50994128e-01,
         6.43655119e-01, -3.63512667e-01,  2.06557840e+00,
        -4.81307952e-01, -1.26146019e-01,  1.26285916e+00,
         1.92106036e+00, -1.40988206e-01, -3.30207380e-01,
        -1.14368404e-01,  4.46404931e-01,  2.63948028e-02,
        -9.04430855e-02,  2.06722357e-01, -1.05571715e-01,
        -3.98447020e-01, -3.97065903e-02,  4.02880398e-01,
         8.48776266e-02,  1.29532474e-01,  7.64022024e-02,
         4.05124169e-01, -1.90886929e-01, -4.86345549e-01,
        -6.11421924e-02,  2.46102055e-01, -9.53221817e-05,
        -3.35678943e-02,  1.43802586e-01,  1.47533347e-01,
        -7.97833822e-02,  4.29964603e-01, -3.50584210e-01,
         6.35976341e-02, -3.82311747e-01, -8.69631016e-02,
         3.73171041e-01, -5.23187471e-01, -6.88186262e-01,
         2.19528537e-01,  5.27956535e-01,  3.72903975e-02,
        -6.54745022e-01,  1.29532474e-01, -8.10567815e-02,
         2.76135738e-01, -1.87667536e-01, -1.40176935e-01,
        -3.50584210e-01, -7.42806929e-01,  4.56035093e-01,
        -7.88457236e-02, -4.57954387e-03,  8.24168424e-01,
         3.77217880e-01, -1.15885122e-01,  2.95087342e-01,
        -1.58546252e-01,  1.29915920e-01, -1.90360653e-01,
         6.21572849e-02,  1.58662849e-01,  3.60785401e-01,
        -2.03489774e-01, -9.45922857e-03,  3.06246896e-02,
        -1.11242806e-01, -3.66378584e-01, -2.63674348e-02,
         3.80140751e-01, -1.08843491e-02, -4.18995166e-02,
        -6.14118029e-01,  6.15947177e-01, -9.47742980e-02,
        -4.16054758e-02,  1.38208922e-01,  1.64118653e-02,
        -1.00909754e-01,  4.38362148e-02,  1.79535640e-01,
        -4.50650707e-02, -9.19797481e-02, -4.75823420e-01,
         1.92145100e-01,  2.93669145e-01, -1.33565847e-01,
         3.00178632e-02,  1.69144908e-01,  4.54412272e-02,
        -1.19199829e-01,  4.57038423e-01,  3.41574300e-01,
         1.28537205e-01,  3.45398310e-03, -1.11001918e+00,
         1.81244415e-01, -2.55219670e-02, -3.21535679e-01,
         2.56130541e-01,  1.19375235e-02,  4.42539595e-02,
         3.65647691e-02, -3.71397165e-02, -2.38576947e-03,
         1.37043590e-01, -7.82288812e-02,  7.62129230e-03,
         1.51121132e-01,  1.82363754e-03,  8.07159024e-02,
        -6.43322874e-03,  9.91664125e-02,  6.27874408e-02,
        -3.44898015e-02,  1.52157952e-02, -2.14449351e-02,
        -3.40334830e-02, -3.23237520e-02,  1.53467842e-02,
        -2.27297489e-02, -4.36158398e-02,  1.61899350e-02,
        -4.53345240e-02,  1.15595090e-01,  2.66411483e-02,
        -6.65657476e-03, -6.60125906e-02, -3.45454163e-02,
        -2.51015966e-02, -8.80069604e-02, -5.54791377e-02,
         4.29627718e-02, -6.00810873e-03,  1.57768183e-01,
         1.91649737e-02, -2.67245781e-03, -1.36386260e-01,
         1.13127021e-01, -4.90685955e-02, -3.82879668e-02,
        -3.33412663e-02, -8.74448367e-02,  4.24839315e-02,
        -4.92368549e-02,  4.57016805e-04,  2.57183852e-02,
        -6.49310535e-02, -2.81045040e-02, -7.45280116e-03,
        -1.59192642e-02,  3.13406652e-02, -7.64603406e-03,
         2.91217920e-03,  5.61433532e-02, -3.44526289e-01,
        -5.49440633e-03, -1.13131221e-02, -6.68137060e-04,
        -9.13683727e-04, -1.47130822e-03, -4.39233577e-01,
        -4.76161450e-05, -1.05924675e-02, -3.23658990e-03,
         9.64265517e-03, -1.98364140e-04, -1.13828009e-02,
        -2.92349578e-03, -6.59565097e-05, -8.28466254e-06,
        -1.99821676e-02, -1.34036745e-02,  5.78137384e-02,
        -5.46334564e-02,  3.65533323e-01,  9.32773000e-02,
         4.36271236e-02, -5.91130918e-03, -9.00907068e-02,
        -6.51004129e-03, -8.60656019e-04, -1.52875716e-05,
        -7.18146127e-03, -9.75968661e-03,  0.00000000e+00,
        -9.12427005e-05, -2.29821128e-02,  7.94679530e-02,
         8.68495373e-02,  2.70059887e-01, -3.02437372e-01,
        -1.62943693e-03, -4.40967760e-01, -2.34798789e-02,
         4.10733874e-01,  1.31422627e-01, -2.53558983e-02,
         2.53542994e-01, -1.01083758e-02, -2.50562386e-01,
         2.62499910e-01, -3.38541618e-01, -2.00884392e-02,
        -1.19536175e-01, -2.32446052e-02,  5.03239985e-01,
        -1.96709762e-02, -1.21818309e-02, -1.29405574e-01,
         2.61079634e-02,  3.38816320e-02,  2.74461536e-03,
        -2.39948928e-02, -2.01516297e-01,  1.21124898e-01,
        -3.14570873e-02,  1.06672143e-02,  1.90140477e-01,
        -5.94686807e-02, -3.82867442e-02,  1.57413659e-02,
        -5.54428862e-02, -1.00611286e-01,  6.69489201e-02,
        -2.09026289e-02, -2.23348092e-02,  1.84195197e-01,
         6.82855035e-02,  3.67533979e-02,  1.23180760e-01,
        -3.99691303e-02, -1.10087089e-01, -1.30539351e-01,
         4.43653744e-02, -1.38291936e-02, -9.59898122e-03,
         4.61455824e-02,  4.72943182e-02,  7.71963853e-02,
         3.05646916e-02, -4.85509386e-02,  4.29955523e-02,
        -1.80979993e-02,  7.38640088e-02, -1.76075391e-02,
        -3.70387057e-02, -8.36002628e-02, -1.61758276e-02,
         0.00000000e+00,  1.34327136e-02, -9.17671515e-02,
        -1.00717251e-01, -6.24773998e-02,  7.93345731e-02,
        -3.16755088e-02, -2.85464763e-02, -7.30935508e-02,
         1.43385689e-02,  2.16620249e-02,  2.73883393e-01,
         5.00262340e-02, -5.26492760e-02, -8.81455658e-02,
         2.06102986e-02, -6.02494799e-02, -7.00940062e-02,
         9.41887569e-02,  1.30628280e-02, -2.86213455e-02,
         2.65366967e-01, -1.65409616e-01, -8.79932740e-03,
         1.67568211e-01, -4.05581008e-02,  1.48579685e-01,
        -9.18614189e-02, -5.37838523e-02, -1.41037212e-02,
        -3.40355264e-02, -2.41428157e-02,  1.66168875e-01,
         9.42934650e-02, -5.69319853e-02,  8.45662550e-02,
         9.40672202e-02, -5.35075268e-02,  3.77025666e-02,
        -2.89165941e-02, -1.44441613e-01, -7.94379356e-02,
        -1.53056443e-01, -2.14726985e-02,  1.99389307e-01,
        -1.94366085e-01, -8.07263628e-02,  3.94736250e-02,
        -1.58239330e-02, -2.86654392e-02, -2.74862363e-02,
         1.11858137e-01,  5.41169887e-03,  6.08444259e-02,
         2.16314341e-02, -5.14128436e-02, -4.49575207e-02,
        -1.34228889e-03, -4.62818405e-02, -5.81590452e-02,
         3.36229045e-02, -1.78062574e-02, -2.05297486e-02,
         3.66238128e-02, -2.28011672e-02,  1.16197081e-02,
         8.87008538e-02, -4.99825860e-02, -1.91716942e-01,
        -8.05483504e-02, -3.59112991e-02, -1.05241920e-02,
        -2.82735671e-02,  1.32899340e-01,  3.64163727e-02,
         3.64403032e-02, -2.05820763e-02,  1.35760914e-01,
         1.73773150e-02, -5.45806664e-02,  4.45960937e-02,
        -1.75216166e-02,  2.56010811e-01, -1.06031970e-01,
        -3.93431757e-02, -5.55970396e-02,  8.83381813e-02,
         3.50462793e-02, -5.64933754e-02, -9.46489780e-03,
         4.24082474e-01, -4.46358916e-01,  2.41055904e-02]])

In [27]:
regressor.coef_.shape

(1, 462)

In [28]:
regressor.intercept_

array([0.00182915])

In [29]:
y_pred_logistic_test = regressor.predict(X_test)

In [30]:
y_pred_logistic_train = regressor.predict(X_train)

In [31]:
print("Logistic regression accuracy for training data:",accuracy_score(Y_train, y_pred_logistic_train))

Logistic regression accuracy for training data: 0.952939856373429

In [32]:
print("Logistic regression accuracy for testing data:",accuracy_score(Y_test, y_pred_logistic_test))

Logistic regression accuracy for testing data: 0.9518399829898395

In [33]:
pd.DataFrame(
    confusion_matrix(Y_test, y_pred_logistic_test),
    columns=['Predicted Income not>50k', 'Predicted Income>50k'],
    index=['True Income not>50k', 'True Income>50k']
)

                     Predicted Income not>50k  Predicted Income>50k
True Income not>50k                     61081                   658
True Income>50k                          2513                  1591

In [34]:
resid = np.array([i[0] for i in Y_train.values.tolist()]) - np.array(y_pred_logistic_train.tolist())
sse = sum(resid**2)
k = 462
n = 65843

AIC = (2*k) - (2*np.log(sse))
BIC = (n*np.log(sse/n)) + (k*np.log(n))

print("AIC of regression model:",AIC)
print("BIC of regression model:",BIC)

AIC of regression model: 906.5062493608599
BIC of regression model: -149483.54010942433

In [35]:
resid = np.array([i[0] for i in Y_test.values.tolist()]) - np.array(y_pred_logistic_test.tolist())
sse = sum(resid**2)
k = 462
n = 65843

AIC = (2*k) - (2*np.log(sse))
BIC = (n*np.log(sse/n)) + (k*np.log(n))

print("AIC of regression model:",AIC)
print("BIC of regression model:",BIC)

AIC of regression model: 907.8763954509233
BIC of regression model: -194590.80461344542

In [ ]:
# Recursive Elimination
m = RFECV(LogisticRegression(), scoring = "accuracy")

m.fit(X_train,Y_train)

In [ ]:
print(len(m.transform(X_train)[0]))

In [ ]:
y_predict_RFECV = m.predict(X_test)

In [ ]:
pd.DataFrame(
    confusion_matrix(Y_test, y_predict_RFECV),
    columns=['Predicted Income not>50k', 'Predicted Income>50k'],
    index=['True Income not>50k', 'True Income>50k']
)

In [37]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,y_pred_logistic_test))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97     61739
           1       0.71      0.39      0.50      4104

   micro avg       0.95      0.95      0.95     65843
   macro avg       0.83      0.69      0.74     65843
weighted avg       0.94      0.95      0.95     65843

## KNN

In [36]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,Y_train)

C:\Users\suraj\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [38]:
y_pred_knn_train = knn.predict(X_train)
y_pred_knn_test = knn.predict(X_test)

In [39]:
#accuracy of knn
print("KNN accuracy for training data:",accuracy_score(Y_train, y_pred_knn_train))

KNN accuracy for training data: 0.9536729503291442

In [40]:
print("KNN accuracy for testing data:",accuracy_score(Y_test, y_pred_knn_test))

KNN accuracy for testing data: 0.9397658065397992

In [41]:
pd.DataFrame(
    confusion_matrix(Y_test, y_pred_knn_test),
    columns=['Predicted Income not>50k', 'Predicted Income>50k'],
    index=['True Income not>50k', 'True Income>50k']
)

                     Predicted Income not>50k  Predicted Income>50k
True Income not>50k                     60781                   958
True Income>50k                          3008                  1096

In [42]:
resid = np.array([i[0] for i in Y_train.values.tolist()]) - np.array(y_pred_knn_train.tolist())
sse = sum(resid**2)
k = 462
n = 65843

AIC = (2*k) - (2*np.log(sse))
BIC = (n*np.log(sse/n)) + (k*np.log(n))

print("AIC of KNN model:",AIC)
print("BIC of KNN model:",BIC)

AIC of KNN model: 906.5376501981239
BIC of KNN model: -150517.30277340903

In [43]:
resid = np.array([i[0] for i in Y_test.values.tolist()]) - np.array(y_pred_knn_test.tolist())
sse = sum(resid**2)
k = 462
n = 65843

AIC = (2*k) - (2*np.log(sse))
BIC = (n*np.log(sse/n)) + (k*np.log(n))

print("AIC of KNN model:",AIC)
print("BIC of KNN model:",BIC)

AIC of KNN model: 907.4289733818405
BIC of KNN model: -179860.9989661364

## LDA

In [44]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=1)  

X_train1 = lda.fit_transform(X_train, Y_train)  
X_test1 = lda.transform(X_test)

C:\Users\suraj\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\suraj\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")

In [45]:
y_pred_lda_train = lda.predict(X_train)
y_pred_lda_test = lda.predict(X_test)

In [46]:
#accuracy of lda
print("LDA accuracy for training data:",accuracy_score(Y_train, y_pred_lda_train))

LDA accuracy for training data: 0.9448234590065829

In [47]:
print("LDA accuracy for testing data:",accuracy_score(Y_test, y_pred_lda_test))

LDA accuracy for testing data: 0.9443524748264812

In [48]:
pd.DataFrame(
    confusion_matrix(Y_test, y_pred_lda_test),
    columns=['Predicted Income not>50k', 'Predicted Income>50k'],
    index=['True Income not>50k', 'True Income>50k']
)

                     Predicted Income not>50k  Predicted Income>50k
True Income not>50k                     60052                  1687
True Income>50k                          1977                  2127

In [49]:
resid = np.array([i[0] for i in Y_train.values.tolist()]) - np.array(y_pred_lda_train.tolist())
sse = sum(resid**2)
k = 462
n = 65843

AIC = (2*k) - (2*np.log(sse))
BIC = (n*np.log(sse/n)) + (k*np.log(n))

print("AIC of LDA model:",AIC)
print("BIC of LDA model:",BIC)

AIC of LDA model: 906.1880264695271
BIC of LDA model: -139007.16519241157

In [50]:
resid = np.array([i[0] for i in Y_test.values.tolist()]) - np.array(y_pred_lda_test.tolist())
sse = sum(resid**2)
k = 462
n = 65843

AIC = (2*k) - (2*np.log(sse))
BIC = (n*np.log(sse/n)) + (k*np.log(n))

print("AIC of LDA model:",AIC)
print("BIC of LDA model:",BIC)

AIC of LDA model: 907.587378548412
BIC of LDA model: -185075.93465741808

# Random Forest

In [51]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(max_depth=2, random_state=0)

rfc.fit(X_train1, Y_train)
y_pred_rfc_train = rfc.predict(X_train1)

C:\Users\suraj\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\suraj\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [52]:
y_pred_rfc_train = rfc.predict(X_train1)
y_pred_rfc_test = rfc.predict(X_test1)

In [53]:
#accuracy of RFC
print("RFC accuracy for training data:",accuracy_score(Y_train, y_pred_rfc_train))

RFC accuracy for training data: 0.9499925194494315

In [54]:
print("RFC accuracy for testing data:",accuracy_score(Y_test, y_pred_rfc_test))

RFC accuracy for testing data: 0.9490758319031636

In [55]:
pd.DataFrame(
    confusion_matrix(Y_test, y_pred_rfc_test),
    columns=['Predicted Income not>50k', 'Predicted Income>50k'],
    index=['True Income not>50k', 'True Income>50k']
)

                     Predicted Income not>50k  Predicted Income>50k
True Income not>50k                     61191                   548
True Income>50k                          2805                  1299

In [56]:
resid = np.array([i[0] for i in Y_train.values.tolist()]) - np.array(y_pred_rfc_train.tolist())
sse = sum(resid**2)
k = 462
n = 65843

AIC = (2*k) - (2*np.log(sse))
BIC = (n*np.log(sse/n)) + (k*np.log(n))

print("AIC of random forest model:",AIC)
print("BIC of random forest model:",BIC)

AIC of random forest model: 906.384757020928
BIC of random forest model: -145483.83004035207

In [57]:
resid = np.array([i[0] for i in Y_test.values.tolist()]) - np.array(y_pred_rfc_test.tolist())
sse = sum(resid**2)
k = 462
n = 65843

AIC = (2*k) - (2*np.log(sse))
BIC = (n*np.log(sse/n)) + (k*np.log(n))

print("AIC of random forest model:",AIC)
print("BIC of random forest model:",BIC)

AIC of random forest model: 907.7647785070675
BIC of random forest model: -190916.2073962979

## Decision Trees

In [58]:
from sklearn.tree import DecisionTreeRegressor
# create a regressor object 
dtr = DecisionTreeRegressor(random_state = 0)  

# fit the regressor with X and Y data 
dtr.fit(X_train,Y_train)

y_pred_dtr_train = dtr.predict(X_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [59]:
y_pred_dtr_train = dtr.predict(X_train)
y_pred_dtr_test = dtr.predict(X_test)

In [62]:
print("Decision Tree accuracy for training data:",accuracy_score(Y_train, y_pred_dtr_train))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [61]:
print("Decision Tree accuracy for testing data:",accuracy_score(Y_test, y_pred_dtr_test))

Decision Tree accuracy for testing data: 0.9318530443631062

In [63]:
pd.DataFrame(
    confusion_matrix(Y_test, y_pred_dtr_test),
    columns=['Predicted Income not>50k', 'Predicted Income>50k'],
    index=['True Income not>50k', 'True Income>50k']
)

                     Predicted Income not>50k  Predicted Income>50k
True Income not>50k                     59462                  2277
True Income>50k                          2210                  1894

In [64]:
resid = np.array([i[0] for i in Y_train.values.tolist()]) - np.array(y_pred_dtr_train.tolist())
sse = sum(resid**2)
k = 462
n = 65843

AIC = (2*k) - (2*np.log(sse))
BIC = (n*np.log(sse/n)) + (k*np.log(n))

print("AIC of decision tree model:",AIC)
print("BIC of decision tree model:",BIC)

AIC of decision tree model: 925.3862943611199
BIC of decision tree model: -771042.9415854823

In [65]:
resid = np.array([i[0] for i in Y_test.values.tolist()]) - np.array(y_pred_dtr_test.tolist())
sse = sum(resid**2)
k = 462
n = 65843

AIC = (2*k) - (2*np.log(sse))
BIC = (n*np.log(sse/n)) + (k*np.log(n))

print("AIC of decision tree model:",AIC)
print("BIC of decision tree model:",BIC)

AIC of decision tree model: 907.182120788048
BIC of decision tree model: -171734.24129959714